PLAYER_IMAGES_DEFAULT_WIDTH = 128
PLAYER_IMAGES_DEFAULT_HEIGHT = 128



PLAYER_ATTACK_UPPER_IMAGE_PATHS = ["256.png", "257.png", "258.png", "259.png"]
PLAYER_ATTACK_UPPER_IMAGE_LOOP_FROM = 0
PLAYER_ATTACK_UPPER_IMAGE_LOOP_TO = len(PLAYER_ATTACK_UPPER_IMAGE_PATHS) - 1
PLAYER_ATTACK_UPPER_IMAGE_GAP = 0.08

PLAYER_ATTACK_NORMAL_IMAGE_PATHS = ["240.png", "241.png", "242.png", "243.png", "248.png", "249.png", "250.png", "251.png"]
PLAYER_ATTACK_NORMAL_IMAGE_LOOP_FROM = 0
PLAYER_ATTACK_NORMAL_IMAGE_LOOP_TO = len(PLAYER_ATTACK_NORMAL_IMAGE_PATHS) - 1
PLAYER_ATTACK_NORMAL_IMAGE_GAP = 0.08

PLAYER_ATTACK_LOWER_IMAGE_PATHS = ["264.png", "265.png", "266.png", "267.png"]
PLAYER_ATTACK_LOWER_IMAGE_LOOP_FROM = 0
PLAYER_ATTACK_LOWER_IMAGE_LOOP_TO = len(PLAYER_ATTACK_LOWER_IMAGE_PATHS) - 1
PLAYER_ATTACK_LOWER_IMAGE_GAP = 0.08

PLAYER_ATTACK_NORMAL_1_IMAGE_PATHS = ["240.png", "241.png", "242.png", "243.png"]
PLAYER_ATTACK_NORMAL_1_IMAGE_LOOP_FROM = 0
PLAYER_ATTACK_NORMAL_1_IMAGE_LOOP_TO = len(PLAYER_ATTACK_NORMAL_1_IMAGE_PATHS) - 1
PLAYER_ATTACK_NORMAL_1_IMAGE_GAP = 0.08

PLAYER_ATTACK_NORMAL_2_IMAGE_PATHS = ["248.png", "249.png", "250.png", "251.png"]
PLAYER_ATTACK_NORMAL_2_IMAGE_LOOP_FROM = 0
PLAYER_ATTACK_NORMAL_2_IMAGE_LOOP_TO = len(PLAYER_ATTACK_NORMAL_2_IMAGE_PATHS) - 1
PLAYER_ATTACK_NORMAL_2_IMAGE_GAP = 0.08

PLAYER_IDOL_IMAGE_PATHS = ["0.png"]
PLAYER_IDOL_IMAGE_LOOP_FROM = 0
PLAYER_IDOL_IMAGE_LOOP_TO = len(PLAYER_IDOL_IMAGE_PATHS) - 1
PLAYER_IDOL_IMAGE_GAP = 0.08

PLAYER_RUN_IMAGE_PATHS = ["1.png", "2.png", "3.png", "4.png", "5.png", "6.png", "7.png", "8.png"]
PLAYER_RUN_IMAGE_LOOP_FROM = 0
PLAYER_RUN_IMAGE_LOOP_TO = len(PLAYER_RUN_IMAGE_PATHS) - 1
PLAYER_RUN_IMAGE_GAP = 0.08

PLAYER_DASH_IMAGE_PATHS = ["64.png", "65.png", "66.png", "67.png", "68.png", "69.png"]
PLAYER_DASH_IMAGE_LOOP_FROM = 4
PLAYER_DASH_IMAGE_LOOP_TO = len(PLAYER_DASH_IMAGE_PATHS) - 1
PLAYER_DASH_IMAGE_GAP = 0.05

PLAYER_SUPER_DASH_IMAGE_PATHS = ["64.png", "65.png", "66.png", "67.png", "68.png", "69.png"]
PLAYER_SUPER_DASH_IMAGE_LOOP_FROM = 4
PLAYER_SUPER_DASH_IMAGE_LOOP_TO = len(PLAYER_SUPER_DASH_IMAGE_PATHS) - 1
PLAYER_SUPER_DASH_IMAGE_GAP = 0.05

PLAYER_JUMP_IMAGE_PATHS = ["144.png", "145.png", "146.png", "147.png", "148.png"]
PLAYER_JUMP_IMAGE_LOOP_FROM = 2
PLAYER_JUMP_IMAGE_LOOP_TO = len(PLAYER_JUMP_IMAGE_PATHS) - 1
PLAYER_JUMP_IMAGE_GAP = 0.08

PLAYER_MID_AIR_JUMP_IMAGE_PATHS = ["144.png", "145.png", "146.png", "147.png", "148.png"]
PLAYER_MID_AIR_JUMP_IMAGE_LOOP_FROM = 2
PLAYER_MID_AIR_JUMP_IMAGE_LOOP_TO = len(PLAYER_JUMP_IMAGE_PATHS) - 1
PLAYER_MID_AIR_JUMP_IMAGE_GAP = 0.08

PLAYER_FALL_IMAGE_PATHS = ["149.png", "150.png", "151.png", "150.png"]
PLAYER_FALL_IMAGE_LOOP_FROM = 0
PLAYER_FALL_IMAGE_LOOP_TO = len(PLAYER_FALL_IMAGE_PATHS) - 1
PLAYER_FALL_IMAGE_GAP = 0.08