# camera modes
CAMERA_MODE_LOCKED_BOTH = 0
CAMERA_MODE_LOCKED_HORIZONTAL = 1
CAMERA_MODE_LOCKED_VERTICAL = 2

CAMERA_MODE_CENTER_LEFT_NORMAL = 3
CAMERA_MODE_CENTER_LEFT_UPPER = 4
CAMERA_MODE_CENTER_LEFT_LOWER = 5

CAMERA_MODE_CENTER_RIGHT_NORMAL = 6
CAMERA_MODE_CENTER_RIGHT_UPPER = 7
CAMERA_MODE_CENTER_RIGHT_LOWER = 8

CAMERA_MODE_BOTTOM_LEFT_NORMAL = 9 
CAMERA_MODE_BOTTOM_LEFT_UPPER = 10
CAMERA_MODE_BOTTOM_LEFT_LOWER = 11

CAMERA_MODE_BOTTOM_RIGHT_NORMAL = 12
CAMERA_MODE_BOTTOM_RIGHT_UPPER = 13
CAMERA_MODE_BOTTOM_RIGHT_LOWER = 14





CAMERA_MODE_CENTER_INDEX = 0
CAMERA_MODE_BOTTOM_INDEX = 1
CAMERA_MODE_LOCKED_INDEX = 2

CAMERA_MODE_UPPER_INDEX = 0
CAMERA_MODE_NORMAL_INDEX = 1
CAMERA_MODE_LOWER_INDEX = 2

CAMERA_MODE_LEFT_INDEX = 0
CAMERA_MODE_RIGHT_INDEX = 1


CAMERA_MODE_LOCKED_BOTH_INDEX = 0
CAMERA_MODE_LOCLED_HORIZONTAL_INDEX = 1
CAMERA_MODE_LOCKED_VERTICAL_INDEX = 2

CAMERA_MODE_MATRIX = [
    [ #CENTER
        [CAMERA_MODE_CENTER_LEFT_UPPER , CAMERA_MODE_CENTER_RIGHT_UPPER ], #UPPER
        [CAMERA_MODE_CENTER_LEFT_NORMAL, CAMERA_MODE_CENTER_RIGHT_NORMAL], #NORMAL
        [CAMERA_MODE_CENTER_LEFT_LOWER , CAMERA_MODE_CENTER_RIGHT_LOWER ], #LOWER
    ],
    [ #BOTTOM
        [CAMERA_MODE_BOTTOM_LEFT_UPPER , CAMERA_MODE_BOTTOM_RIGHT_UPPER ], #UPPER
        [CAMERA_MODE_BOTTOM_LEFT_NORMAL, CAMERA_MODE_BOTTOM_RIGHT_NORMAL], #NORMAL
        [CAMERA_MODE_BOTTOM_LEFT_LOWER , CAMERA_MODE_BOTTOM_RIGHT_LOWER ], #LOWER
    ],
    [ #LOCK
        [CAMERA_MODE_LOCKED_BOTH       , CAMERA_MODE_LOCKED_BOTH        ], # LOCKED
        [CAMERA_MODE_LOCKED_HORIZONTAL , CAMERA_MODE_LOCKED_HORIZONTAL  ], # LOCKED HORIZONTAL
        [CAMERA_MODE_LOCKED_VERTICAL   , CAMERA_MODE_LOCKED_VERTICAL    ], # LOCKED VERTICAL
    ]
]





CAMERA_VISIBLE_EXTENSION_LENGTH_RATIO = 1

CAMERA_MODE_BOTTOM_OFFSET_TARGET_RATIO = 1

CAMERA_SHIFTING_TARGET_RATIO_HORIZONTAL = 1
CAMERA_SHIFTING_TARGET_RATIO_VERTICAL = 1

CAMERA_LOCKING_VELOCITY_RATIO_HORIZONTAL = 0.5
CAMERA_LOCKING_VELOCITY_RATIO_VERTICAL = 0.5

CAMERA_SHIFTING_VELOCITY_RATIO_HORIZONTAL = 0.05
CAMERA_SHIFTING_VELOCITY_RATIO_VERTICAL = 0.05

CAMERA_FOLLOW_VELOCITY_RATIO_POSITIVE_HORIZONTAL = 1
CAMERA_FOLLOW_VELOCITY_RATIO_NEGATIVE_HORIZONTAL = 1
CAMERA_FOLLOW_VELOCITY_RATIO_POSITIVE_VERTICAL = 1
CAMERA_FOLLOW_VELOCITY_RATIO_NEGATIVE_VERTICAL = 0.05

CAMERA_FOLLOW_MAX_VELOCITY_RATIO_POSITIVE_HORIZONTAL = 1
CAMERA_FOLLOW_MAX_VELOCITY_RATIO_NEGATIVE_HORIZONTAL = 1
CAMERA_FOLLOW_MAX_VELOCITY_RATIO_POSITIVE_VERTICAL = 1
CAMERA_FOLLOW_MAX_VELOCITY_RATIO_NEGATIVE_VERTICAL = 1