FPS = 60

INFORMATION_FONT_SIZE = 16
INFORMATION_LINE_HEIGHT = 16



from win32api import GetSystemMetrics

WINDOW_DESIGN_WIDTH = 1920
WINDOW_DESIGN_HEIGHT = 1080

WINDOW_DEFAULT_WIDTH = GetSystemMetrics(0)
WINDOW_DEFAULT_HEIGHT = GetSystemMetrics(1)

GAME_SIZE_RATIO = WINDOW_DEFAULT_HEIGHT / WINDOW_DESIGN_HEIGHT



GAME_GRAVITY = 4



RESPAWN_TYPE_SAVE_POINT = 0
RESPAWN_TYPE_NO_RESPAWN = 1
RESPAWN_TYPE_NEAREST_GROUND = 2



COLLIDEBOX_DISPLAY_COLOR = (0, 0, 255)
DAMAGEBOX_DISPLAY_COLOR = (255, 0, 0)