FPS = 60

INFORMATION_FONT_SIZE = 16
INFORMATION_LINE_HEIGHT = 16



from win32api import GetSystemMetrics

SCREEN_WIDTH = GetSystemMetrics(0)
SCREEN_HEIGHT = GetSystemMetrics(1)

GAME_WIDTH = 1920
GAME_HEIGHT = 1080

SCREEN_GAME_RATIO = min(
    SCREEN_WIDTH  / GAME_WIDTH ,
    SCREEN_HEIGHT / GAME_HEIGHT
)

DISPLAY_OFFSET_X = round( ( (SCREEN_WIDTH /SCREEN_GAME_RATIO) - GAME_WIDTH  ) / 2 )
DISPLAY_OFFSET_Y = round( ( (SCREEN_HEIGHT/SCREEN_GAME_RATIO) - GAME_HEIGHT ) / 2 )



GAME_GRAVITY = 4



RESPAWN_TYPE_SAVE_POINT = 0
RESPAWN_TYPE_NO_RESPAWN = 1
RESPAWN_TYPE_NEAREST_GROUND = 2



COLLIDEBOX_DISPLAY_COLOR = (0, 0, 255)
DAMAGEBOX_DISPLAY_COLOR = (255, 0, 0)