#gameplay
PLAYER_HEALTH_FRAME_OFFSET_X = 128
PLAYER_HEALTH_FRAME_OFFSET_Y = 64
PLAYER_HEALTH_FRAME_WIDTH = 233
PLAYER_HEALTH_FRAME_HEIGHT = 144

PLAYER_HEALTH_BLOCK_OFFSET_X = 252
PLAYER_HEALTH_BLOCK_OFFSET_Y = 88
PLAYER_HEALTH_BLOCK_WIDTH = 38
PLAYER_HEALTH_BLOCK_HEIGHT = 47
