PLAYER_CLIFF_DETECTION_DISTANCE_HORIZONTAL_MULTIPLIER = 3
PLAYER_CLIFF_DETECTION_DISTANCE_VERTICAL_MULTIPLIER = 0.2

PLAYER_ATTACK_TIME = 0.2
PLAYER_ATTACK_DAMAGE = 15
PLAYER_ATTACK_KNOCKBACK_TIME = 0.4
PLAYER_ATTACK_KNOCKBACK_VELOCITY = 16
PLAYER_ATTACK_KNOCKBACK_MAX_VELOCITY = 32

PLAYER_DASH_COOLDOWN = 1
PLAYER_DASH_MAX_VELOCITY = 24
PLAYER_DASH_ACCELERATION = 1.5
PLAYER_DASH_TIME = 0.3

PLAYER_SUPER_DASH_HELD_TIME = 2
PLAYER_SUPER_DASH_MAX_VELOCITY = 24
PLAYER_SUPER_DASH_ACCELERATION = 1.5

PLAYER_MID_AIR_JUMP_TIME = 0.3

PLAYER_VELOCITY_HORIZONTAL = 8
PLAYER_VELOCITY_VERTICAL = 16
PLAYER_TERMINAL_VELOCITY_VERTICAL = 16

PLAYER_JUMP_HELD_MAX_TIME = 0.4

PLAYER_COLLIDEBOX_DISPLAY = False
PLAYER_DAMAGEBOX_DISPLAY = False
